[package]
name = "wolfconf"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1.37", features = ["full"] }
hyper = { version = "0.14", features = ["server", "tcp"] }
uuid = { version = "1.4", features = ["v4"] }
tower = "0.4" 
tower-http = { version = "0.6.0", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
